name: Publish stage version

on:
  push:
    branches:
      - "develop"

env:
  OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
  OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
  SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
  SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
  SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: gradle

    - name: Download NDK 21
      run: |
        wget --quiet --output-document=android-ndk.zip "http://dl.google.com/android/repository/android-ndk-r21d-linux-x86_64.zip"
        rm -rf /usr/local/lib/android/sdk/ndk/23.0.7599858/
        mkdir /usr/local/lib/android/sdk/ndk/23.0.7599858/
        unzip -q android-ndk.zip
        cd android-ndk-r21d
        cp -r . /usr/local/lib/android/sdk/ndk/23.0.7599858/
        #ls /usr/local/lib/android/sdk/ndk/23.0.7599858/

    - name: Install rust dependencies
      run: rustup target add armv7-linux-androideabi | rustup target add aarch64-linux-android | rustup target add i686-linux-android | rustup target add x86_64-linux-android | rustup target add x86_64-unknown-linux-gnu

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Kotlin linter
      run: ./gradlew ktlint

    - name: Run Unit tests
      run: ./gradlew testDebugUnitTest

    - name: Publish to staging Maven
      run: ./gradlew publishReleasePublicationToSonatypeRepository --max-workers 1 closeSonatypeStagingRepository
